'Used: https://docs.python.org/3/tutorial/controlflow.html'

# "range()" Function
# If you want to iterate over a sequence of numbers, you can use the "range()" function
for x in range(5): # The "for" statement gets add the elements in sequence from the list generated by the "range(int)" function! 
    print(x, end=', ') # This will print all the elements in the list created by the above statement and will add a ", " string at the end of every element to avoid newlines!
# The range(int) function creates a list of numbers from 0 to the number specified excluding it. Thats why the above will print out "0, 1, 2, 3, 4, " and will exclude the "5"
# In short, it will create a list with the number of elements as the number you specify starting with "0" and going in the following sequence: "0, 1, 2, 3,...."

# Another example with the "input" function we learnt in the "statements.py" file 
'Used: statements.py'
input = int(input('\nInput a number to get the range of numbers till it: ')) # This will send the message in the command prompt and the answer(an int) will be stored as the variable "input"
for i in range(input): # The "input" variable got from the previous statement will decide how long the list is to be printed
    print(i, end=', ') # This will print all the elements of the list "input" in a sequence because of the "for" statement above

